-- User
-- CREATE USER atlas;
CREATE USER atlas LOGIN PASSWORD 'atlas' NOCREATEDB NOCREATEROLE NOREPLICATION VALID UNTIL 'infinity';

-- Database
CREATE DATABASE atlas;
GRANT ALL PRIVILEGES ON DATABASE atlas TO atlas;

-- Schema
\connect atlas;
CREATE SCHEMA atlas AUTHORIZATION atlas;
-- CREATE SCHEMA atlas;
-- ALTER SCHEMA atlas OWNER TO atlas;