server:
  contextPath: /hydra
endpoints:
  jmx:
    domain: atlas
logging:
  config: 'classpath:atlas-logback.xml'
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create # create-drop
    properties:
      net.sf.ehcache.configurationResourceName: atlas-ehcache.xml
      hibernate:
        default_schema: atlas
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  datasource:
    url: 'jdbc:postgresql://192.168.1.7:5432/atlas?currentSchema=atlas'
    username: atlas
    password: atlas
    driver-class-name: org.postgresql.Driver
flyway:
  enabled: true
  table: DB_MIGRATION_HISTORY
  sqlMigrationSuffix: .Final.sql
  schemas: atlas
application:
  roles:
    admin:
      username: admin
      password: iotac
    user:
      username: user
      password: iotac