logging:
  config: logback.xml
    #${catalina.base}/config-overrides/atlas-logback.xml
endpoints:
    jmx:
        domain: atlas
spring:
    jpa:
        #database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        #properties:
        #        default_schema: atlas
        hibernate:
                ddl-auto: create-drop
    datasource:
        url: jdbc:postgresql://localhost:5432/atlas #?currentSchema=atlas
        username: atlas
        password: atlas
        driver-class-name: org.postgresql.Driver
flyway:
    enabled: true
    table: DB_MIGRATION_HISTORY
    sqlMigrationSuffix: .Final.sql
    schemas: atlas
application:
    roles:
        admin: app_user