server:
  # Configuration of Spring Boot embedded Tomcat server (java -jar atlas.war)
  servlet:
    contextPath: '/atlas'
  port: 8443
  http:
    port: 8080
  ssl:
    enabled: true
    key-store: 'classpath:ssl/atlas.keystore' #'${catalina.home}/conf/atlas.keystore'
    keyAlias: iotacsystems.com
    key-store-password: iotacsystems
    keyStoreType: PKCS12
endpoints:
  jmx:
    domain: atlas
logging:
  config: 'classpath:atlas-logback.xml'
spring:
  jmx:
    default-domain: atlas
  data:
    rest:
      defaultMediaType: application/json
  jpa:
    generate-ddl: true
    show-sql: true
    #hibernate:
      #ddl-auto: create-drop # create | update | validate | create-drop
    properties:
      net.sf.ehcache.configurationResourceName: atlas-ehcache.xml
      hibernate:
        default_schema: atlas
        generate_statistics: false
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  datasource:
    url: 'jdbc:postgresql://rdbms:5432/atlas?currentSchema=atlas'
    username: atlas
    password: atlas
    driver-class-name: org.postgresql.Driver
flyway:
  enabled: true
  table: DB_MIGRATION_HISTORY
  sqlMigrationSuffix: .Final.sql
  schemas: atlas
mqtt:
  broker:
    url: "tcp://broker:1883" # tcp://broker.hivemq.com:1883
    auth:
      username: atlas
      password: atlas #"d3d3LmludGVybmV0LW9mLXRoaW5ncy1hbnRvbmFrb3MtY2Fyb3V6b3Mtc3lzdGVtcy5jb20=" # "Base64(www.internet-of-things-antonakos-carouzos-systems.com)"
      hash-algorithm: null # "SHA-512"
      hash-salt: null #"d3d3LmludGVybmV0LW9mLXRoaW5ncy1hbnRvbmFrb3MtY2Fyb3V6b3Mtc3lzdGVtcy5jb20=" # "Base64(www.internet-of-things-antonakos-carouzos-systems.com)"
  client:
    id: "org.iotac.atlas"
  service:
    quality: 1 # 0,1 or 2
    retained: false
application:
  roles:
    admin:
      access-token: admin # Change in PRD with a UUID
  cron:
    actions:
      lookup-rate: 10000
    alerts:
      lookup-rate: 10000
