logging:
  config: 'classpath:atlas-logback.xml'
  # config: ${catalina.base}/config-overrides/atlas-atlas-logback.xml
endpoints:
  jmx:
    domain: atlas
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create # create-drop
    properties:
      hibernate:
        default_schema: atlas
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: 'jdbc:postgresql://192.168.1.7:5432/atlas?currentSchema=atlas'
    username: atlas
    password: atlas
    driver-class-name: org.postgresql.Driver
flyway:
  enabled: true
  table: DB_MIGRATION_HISTORY
  sqlMigrationSuffix: .Final.sql
  schemas: atlas
application:
  roles:
    admin: app_user